wfdb/readwrite/downloads.py
Downloading the mghdb give the following error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1209: ordinal not in range(128)
import wfdb
wfdb.dldatabase('mghdb', os.getcwd(), records = 'all', annotators = 'all' , keepsubdirs = True, overwrite = False)
It s look like text isn t just ascii, but latin 1.
=> UnicodeDecodeError when downloading mghdb

wfdb/processing/basic.py
=> fix resample-multichan and resample-singlechan

wfdb/plot/plot.py
Fixes error discussed in #144.
=> Unnecessary argument in plt.show(). Fixes #144

wfdb/plot/plot.py
"Demo 7" in the sample notebook raises a type error (https://github.com/MIT-LCP/wfdb-python/issues/168) because `sig_units` contains None:
```
(Pdb) sig_name
['II', 'V', 'MCL1', 'ABP']
(Pdb) sig_units
[None, 'mV', 'mV', None]
```
The error is raised when `sig_name` or `sig_units` are not strings (e.g. int or null). This fixes the error.
=> signal name and unit as strings. fixes #168.

tests/test_processing.py, wfdb/processing/evaluate.py
addresses #151 and #182 
- sensitivity correctly calculated as TP / (TP+FN)
- PPV correctly calculated as TP / (TP + FP)
- removed "false positive rate" as that is commonly accepted to be 1 - specificity, which was not calculated by the function
=> fix: calc sens correctly and remove erroneously labeled FPR

wfdb/processing/evaluate.py
Fixes missing parenthesis `evaluate.py` which formats the printing of false positives. Fixes #181.
=> Fixes missing parenthesis #181

wfdb/io/record.py
Raises error in `wrsamp` if the user attempts to input a record name with a "." since this would indicate an EDF file which is currently not available.
=> Raises error for invalid records file name #177

wfdb/io/record.py
Fixes the URL path issue in `wfdb.dl_database` to include a trailing slash to prevent an "HTTPError: 404 Client Error". This has been noted in both issues #166 and #174.
=> Fixes URL path issues #166

wfdb/processing/qrs.py
Fixes the truncated comment seen in the docstrings of the `__init__` method in the `Conf` class in `qrs.py` and fixes the false `ValueError` help traceback statement for `hr_min`.
=> Fixes comment and ValueError in qrs.py #161

wfdb/io/_signal.py
Fixes the call of the function `_wfdb_fmt` inside of the `_wfdb_fmt` function of the `_signal.py` file.
=> Fixes _wfdb_fmt #148

.gitignore
Adds more to `.gitignore` for VS Code users as well as users who name their virtual environment "venv" instead of "env"
=> Adds more to .gitignore

wfdb/io/annotation.py, wfdb/plot/plot.py
Adds a more descriptive error message when the user attempts to plot waveform data using `plot_wfdb()` when reading in both record and annotation data while using the `sampfrom` and `sampto` parameters. Instead, directs users to utilize the `shift_samps=True` parameter of the `rdann` function to prevent the `IndexError`. Fixes #162.
=> More descriptive annotation error message #162

wfdb/processing/basic.py
Fixes the freezing seen in `resample_ann` when the `fs_target` is set too high. This causes the algorithm to develop an infinite loop which must be exited upon discovery. This pull request breaks the loop if this situation is detected. Fixes #116.
=> Fixes resample_ann freezing #116

wfdb/io/annotation.py
Adds more information about annotation labels and classes such as naming conventions and file extension types as well as label descriptions. Fixes #143.
=> Makes annotation documentation clearer #143

wfdb/io/_signal.py, wfdb/io/record.py
Adds a datatype parameter in the `rdrecord` and `rdsamp` functions to allow the user to increase computation speed at the expense of accuracy and significant figures of signal data. Fixes #224 and #225.
=> Adds datatype parameter in rdrecord/rdsamp #224 #225

docs/conf.py
Fixes ImportError with ReadTheDocs where `requests` can't be imported.. probably because it is already being mock imported.
=> Fixes ReadTheDocs build error

wfdb/io/_header.py
Fixes #231 
with the change the output is
```
sig_name   units  adc_res  init_value  checksum  block_size
0           Chin      uV       15           0     24244           0
1       Left Leg      uV       15           0     22989           0
2      Right Leg      uV       15           0    -22154           0
3  CPAP Pressure  mcmH2O       15           0    -24985           0
4      CPAP Flow   l/min       15           0    -22447           0
5      CPAP Leak   l/min       15           0     10563           0
6       Light_BU       m       15           0     17314           0
7       XFlow_DR    mV/s       15           0    -12675           0
```
=> updated regex to correctly parse units

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
Adds the `signame` function from the [original WFDB software package](https://www.physionet.org/physiotools/wag/signam-1.htm). This version maintains the original functionality including the `-s` option for specific signal numbers. Since the `-h` option just prints help for the function, this was omitted since it can be recreated using `help(wfdb.signame)`.
=> Adds original signame function

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/annotation.py
Adds the `ann2rr` function from the [original WFDB software package](https://www.physionet.org/physiotools/wag/ann2rr-1.htm). This version sets the `-A` option as the default in place of `-c`. Both the `-f` and `-t` options are conserved which specify the desired start and stop time. The `-h` option can be found using `help(wfdb.ann2rr)`. The `-i` option is conserved except for the `t` parameter and specified number of decimal places. All the other options were not conserved since they can be determined using the current framework.
=> Adds original ann2rr function

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/_header.py, wfdb/io/_signal.py, wfdb/io/annotation.py, wfdb/io/download.py, wfdb/io/record.py, wfdb/plot/__init__.py, wfdb/plot/plot.py, wfdb/processing/__init__.py, wfdb/processing/basic.py, wfdb/processing/evaluate.py, wfdb/processing/peaks.py, wfdb/processing/qrs.py
Converts all relative imports to absolute as per PEP8 guidelines. According to [documentation](https://www.python.org/dev/peps/pep-0008/#imports)... "Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on `sys.path`)". I actually encountered the previous error on #236 and had a tough time tracking down the error which prompted me to make this switch.
=> Converts relative imports to absolute

wfdb/io/_signal.py
Fixes error when using the `return_res` parameter which can sometimes modify the format in which the data from file is read. This oftentimes creates illogical arrays which can't be recovered into the proper values or even the proper shape. Fortunately, the removal of this does not significantly affect the runtime of the function even for large arrays. Fixes #230.
=> Fixes return_res error #230

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
Introduces the conversion of WFDB files to MAT format. All data was written to the `.mat` file using `struct.pack()` so no outside packages were introduced.
This implementation conserves the `-f` and `-t` options for setting a desired start and stop time respectively, though the units here are samples instead of seconds. The `-h` option can be used using `help(wfdb.wfdb2mat)`. The `-H` option can not be implemented here at the moment since all high-resolution content is read first through the `rdrecord` function which must be changed to allow this. The `-l` option can be used with the `-f` and `-t` options in combination. The `-s` option is implemented by allowing the user to select their desired channels based on the integer value of the signal number. The `-S` option was not implemented …
=> Produces MAT file from WFDB format

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/_signal.py, wfdb/io/record.py
Introduces the conversion of WFDB files to EDF format. All data was written to the EDF file using `struck.pack()` so no outside packages were introduced. This implementation conserves the `-h` option which can now be used with `help(wfdb.wfdb2edf)`. Further, the `-v` option was conserved and is no longer an option so all content will be printed to screen to help the user see what is going on and the specifications of their EDF file. The `-o` option, which is used to specify their desired EDF file name, is also conserved. The default behavior is that an input record named "100" would now produce an EDF file named "100.edf".
=> Produces EDF file from WFDB format

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
Introduces the conversion of WFDB files to WAV format. All data was written to the WAV file using `struct.pack()` and `numpy.tofile()` so no outside packages were introduced. This implementation conserves the `-h` option which can now be used with `help(wfdb.mit2wav)`. Further, the `-o` option, which is used to specify their desired WAV file name, is also conserved in the form of the parameter `output_filename`. Finally, the `-n` option is conserved which is used to specify whether or not to write an accompanying header file. This is now in the parameter `write_header`.
=> Produces WAV file from WFDB format

wfdb/processing/basic.py
Fixes error when downsampling single channel if NaN values are present. This was a Scipy issue so extra pre-processing and input validation was done to help safe-guard against this issue re-occuring in the future. Fixes #249.
=> Fixes downsample error #249

wfdb/io/download.py, wfdb/io/record.py
Fixes URL generation for Windows machines by removing the `os.sep` operation. Fixes #247.
=> Fixes erroneous URL #247

wfdb/io/record.py
Fixes URL path error generated on Windows machines while trying to read and download certain content. Fixes #254.
=> Fixes download on Windows #254

wfdb/io/annotation.py
Fixes the deprecation of `.loc` being used with missing labels and replaces it with the suggested `.reindex()`. Fixes #255.
=> Fixes Pandas .loc update for annotations #255

wfdb/io/annotation.py
Fixes the `NameError` that occurs when incorrect `return_label_elements` are provided while trying to read an annotation file. Fixes #253.
=> Fixes NameError in annotation except statement #253

requirements.txt, setup.py
I just did `pip install wfdb` and noticed that there are some dependencies that can probably be removed. The package `sklearn` is not a real package (you want `scikit-learn`) so it should be removed. I've also moved `nose` to `extras_require` because it is not required for normal usage (I've kept it in `requirements.txt` though). Finally, I think `six` is never used in the project so I've removed it. Not sure if there are more unused dependencies, but these are probably the most important fixes. Let me know what you think.
=> Prune requirements

wfdb/io/download.py
Replaces `os.sep` with `/` to indicate a URL and prevent issues on Windows machines since `os.sep` on Windows is `\`. Fixes #262.
=> Fixes download fail on Windows #262

wfdb/processing/evaluate.py
Currently evaluation fails if either reference or detected qrs has only one value
=> Add size check before monotonicaly check

wfdb/io/annotation.py, wfdb/io/record.py
Similar error causing the issue mentioned in #254 where some paths were being split using the OS default file path separator which caused problems for Windows users.
=> Fixes path parsing for Windows

setup.py
This change relaxes the requirements for the `pytz` package from `>=2018.3` to `>= 2017.2` since it is only required by `pandas` which only requires `pytz>=2017.2`.
=> Relaxes requirements for pytz

wfdb/io/annotation.py
`symbol` needs to be defined in `calc_core_bytes` so the annotations can be converted into bytes for writing.  I added this to define `symbol` when `label_store` is being used:
```
if 'symbol' not in present_label_fields:
self.convert_label_attribute(source_field=present_label_fields[0],
target_field='symbol')
```
=> Fixes NoneType error in wfdb.io.wrann when using label_store instead of symbol #260

docs/io.rst, docs/wfdb.rst, wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
This change adds a CSV to WFDB converter. This function only explicitly requires the sample rate (`fs`) and units (`units`) to be defined. The rest of the information will be interpreted based on the signal provided and common default values unless explicitly stated by the user attempting the conversion. The user may either choose to only return the record (`record_only=True`), write the file (nothing must be explicitly stated as this is the default behavior), turn on verbosity to display the computed values to adjust if needed (`verbose=True`), set a custom delimiter (`delimiter='\t'`), and specify if a header is being used (`header=False`).
In addition to the CSV being required to follow [RFC guidelines](https://tools.ietf.org/html/rfc4180#section-1), it must also adhere to the …
=> Adds CSV to WFDB converter

wfdb/plot/plot.py
=> Update plot.py to include sharex, sharey

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/annotation.py
This change does two things:
1. `ann2rr`:
- Cleans up the docstrings
- Adds new `as_array` parameter which will print the RR intervals as a Numpy array
2. `rr2ann`:
- Implements the `rr2ann` function from the [original WFDB package](https://www.physionet.org/physiotools/wag/ann2rr-1.htm#sect4)
- Allows users to convert either only RR intervals or both RR intervals and annotation symbols to an annotation file
- The user can also input the RR intervals as either samples between events or time of occurence
=> Cleans up ann2rr; adds rr2ann

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
This change adds the `wfdbdesc` function from the [original WFDB package](https://www.physionet.org/physiotools/wag/wfdbde-1.htm). The only difference here is that I chose to limit the description of multi-segment headers to just the header itself instead of diving into each of the records it calls (I thought this might be a bit more consistent behavior). This can be added as a feature later though.
=> Adds wfdbdesc function

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/record.py
This change adds the `wfdbtime` function from the [original WFDB package](https://www.physionet.org/physiotools/wag/wfdbti-1.htm). All of the original functionality should still be available, however the method used to input the arguments is different. For this implementation, users must provide their desired time argument as either a single string or list of multiple strings.
The input formats are also the same, which is an integer (in which case '1' will be interpreted as 1 second), a datetime format (hh:mm:ss.sss DD/MM/YYYY), or prefixed with the letter 's' if the time at a selected sample is desired (i.e. 's10' for sample time). For the datetime format, 0's do not have be filled for all values (i.e. '5::' will be interpreted as '05:00:00.000',  ':5:' will be '00:05:00.000', etc.). The …
=> Adds wfdbtime function

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/annotation.py
This change adds the ability for users to convert their CSV files of signal annotations into WFDB format.
The CSV must format the annotations as onset (in either time or sample format, where a sample rate is required for time format to convert to sample number) in the first column, and either a description in the second column, or a time duration in the second column if the annotations span over a length of time and description in the third column (see docstrings for examples).
The user may specify the delimiter of the input file so CSV, TSV, etc. are all supported. The user may also choose to omit the header if they feel that works better for their pipeline (header must be exactly either `onset,description` or `onset,duration,description`). 
Future additions will allow the user to …
=> Adds CSV to WFDB-Annotation function

wfdb/io/annotation.py
As seen in the original WFDB C package [source code](https://archive.physionet.org/physiotools/wfdb/app/rdann.c), subtypes ranging from -128 to 127 are now allowed, though currently WFDB-Python only supports 0-127. This change fixes that discrepancy.
Fixes #248.
=> Allow annotation negative subtypes #248

wfdb/io/_header.py
Every time I look at a header file I have to remind myself of what exactly the format is and what the separators (`:`, `+`, etc.) mean. Therefore, a while back, a put together what a header file would look like given that every field is filled. I decided that it would be useful for others to have this information also so I'm adding it in this pull request.
=> Adds extra header information

wfdb/io/record.py
It seems like sometimes Github Actions runs into issues when using `requests.get()`, specifically the error:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='physionet.org', port=443): Max retries
exceeded with url: /content/wfdb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object
at 0x119995640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not
known'))
```
I think this is, at least in part, due to the lack of the extra forward slash in the `wfdb.io.record.get_version` function. To confirm, I did some analysis into the request history:
```
>>> requests.get('https://physionet.org/content/wfdb/').history
[<Response [302]>]
>>> requests.get('https://physionet.org/content/wfdb').history
[<Response [301]>, <Response …
```
=> Fixes request redirect bug

wfdb/__init__.py, wfdb/io/__init__.py, wfdb/io/annotation.py, wfdb/io/record.py
This change add the `sigavg` function from the [original WFDB package](https://physionet.org/physiotools/wag/sigavg-1.htm). So far, I have included the `-d`, `-f`, `-t`, and `-v` flags with intentions to add the flags ~~`-p`~~ (done in 7ed6c24) and `-z` before merging. For this implementation I decided to allow the user to both print the output like in the original package and return it as a Pandas dataframe for easy lookup and access when piping it to another function.
=> Adds sigavg function

tests/test_plot.py, wfdb/plot/plot.py
Unable to plot a record with only one channel
In `plot.py`: `plot_signal()`, `plot_annotation()` and `plot_ecg_grids()` uses `axes` as lists, e.g. :
```python
if signal.ndim == 1:
axes[0].plot(t, signal, sig_style[0], zorder=3)
```
```python
>>> import wfdb
>>> record = wfdb.rdrecord('sample-data/100', sampto=3000)
>>> wfdb.plot_wfdb(record)
>>> record2 = wfdb.rdrecord('sample-data/100', sampto=3000, channel_names=['V5']) 
>>> wfdb.plot_wfdb(record2)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\git\wfdb-python\wfdb\plot\plot.py", line 642, in plot_wfdb
return plot_items(signal=signal, ann_samp=ann_samp, ann_sym=ann_sym, fs=fs,
File "C:\git\wfdb-python\wfdb\plot\plot.py", line 119, in plot_items
plot_signal(signal, sig_len, n_sig, fs, time_units, …
```
=> bugfix: unable to plot single channel record

wfdb/io/_signal.py
If we are reading a record in "non-smooth-frames" mode, we need to extract an array of samples for each signal, which may require copying a non-contiguous sequence of samples into a new array.
Previously, this was done through a complicated Python loop that created an array of all the desired sample indices (i.e., if the signal contains 1,000,000 samples, this would generate an array of 1,000,000 integers) and using that array to index into the raw sample array.  This is rather slow.
A better way is to treat the raw sample array as a 2D array, extract a slice, and then reshape that slice into a 1D array.  This means the work is done within numpy and is very fast.
This shouldn't have any user-visible effects, apart from better performance, and is independent of pull #313.
Example:
```
$ …
```
=> Optimize smooth_frames=False

wfdb/io/_header.py
* Hyphens should be permitted in segment names.  Currently hyphens are permitted in record names and signal file names, but not in segment names.
* When parsing a line in a header file, we must start at the beginning of the line.  Currently we search for the expected pattern *anywhere within the line*, which means any "junk" at the start of the line is silently ignored.
This means that if a multi-segment record includes a segment with a hyphen in the name, everything up to and including the hyphen is silently ignored.
A related problem occurs if there are slashes in a segment or signal file name.  Although subdirectories are permitted in WFDB format, wfdb-python currently doesn't support them, so these should raise an exception rather than being silently ignored.
=> Allow hyphens in segment names, and fix basic parsing issues

tests/test_record.py, wfdb/io/_signal.py, wfdb/io/download.py
WFDB format 24 consists of 24-bit signed integers (each sample is stored as three bytes on disk.)  When reading the signal data into memory, it therefore must be converted into some format that the CPU can work with, such as 16-bit or 32-bit integers.
Previously, this was done by silently discarding the least significant byte and storing the samples as 16-bit integers.  This loses precision, which is rather a bad thing if you actually have a reason for using 24-bit signal files.  Additionally, since `rdrecord` didn't make any corrections to the gain/baseline, the resulting physical values were completely wrong.
Furthermore, the conversion was done in a messy and very buggy way in `_rd_dat_file` (failing to handle `sampfrom`/`sampto`, failing to handle prologs, and failing to handle an odd …
=> Fix reading 24-bit signals (format 24)

sample-data/a103l-no-len.hea, sample-data/drive02-no-len.hea, tests/test_record.py, wfdb/io/_signal.py, wfdb/io/record.py
If the header file does not specify the signal length, `rdrecord` tries to determine it based on the length of the first signal file.
This calculation was wrong when the signal file contained a prolog, or any signal contained multiple samples per frame.
=> Correctly infer length of record when unspecified

docs/conf.py, requirements.txt, setup.py, wfdb/processing/basic.py, wfdb/processing/qrs.py
As far as I can tell, `scikit-learn` is only used in the module [processing.qrs](https://github.com/MIT-LCP/wfdb-python/blob/408ad93324c6c2f8c41aaaf51ddc974372cbf837/wfdb/processing/qrs.py#L6). The two uses of the imported function [`normalize`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html) could be handled by a [simple implementation in `wfdb`](https://github.com/hofaflo/wfdb-python/blob/0e237dfc96e85a9ef6917a049517f4b7adb563b5/wfdb/processing/basic.py#L235-L250). This would allow `wfdb` to remove `scikit-learn` as a requirement and speed up the import time of `wfdb.processing`.
=> Remove dependency on scikit-learn

tests/test_url.py, wfdb/io/_url.py, wfdb/io/download.py, wfdb/io/record.py, wfdb/processing/evaluate.py
When reading remote files via HTTP(S), currently a variety of ad-hoc methods are used: e.g., there's one function for retrieving and parsing a header file, another function for retrieving a segment of a signal file, and another for retrieving an annotation file.
This isn't conducive to reading complex data formats, because every format needs to be implemented twice (once using the standard file API, for local files, and once using the requests API, for remote files.)  This leads to bugs and inconsistencies.
Furthermore, it is desirable to reuse sockets, set a meaningful User-Agent, and retain cookies.  This requires handling all of the package's HTTP requests in a central place, rather than each function calling `requests.get` or `requests.head`.
This pull request introduces a function …
=> HTTP file I/O backend

setup.py
The page comparing install_requires vs requirements files changed its link
=> Update doc link in setup.py

wfdb/io/_signal.py, wfdb/io/record.py
If a parameter X is documented as having a boolean value, it should be treated (in duck-typing style) as true if bool(X) is true, or false if bool(X) is false.
Writing "if X is True" is almost always a bad idea: it suggests to the reader that "X is True" and "X is False" are the only possibilities, when in fact there is no such guarantee.
(In some cases it might make sense to explicitly check argument types to catch programming errors - but in most cases this feels like an overcomplication, and *even then* it's a bad idea to write "if X is True" because the permitted argument types might change in the future.)
To wit: `rdrecord("foo", physical=0)` would do what you expect; `rdrecord("foo", physical=1)` would crash.  `rdrecord("foo", smooth_frames=1)` would do what you expect; …
=> Eliminate "is True" and "is False"

wfdb/plot/plot.py
When plotting signals and annotations using `wfdb.plot_items` or `wfdb.plot_wfdb
`, the annotation markers are currently displayed "underneath" the signal trace, where they are hard to see.  Put them "on top" instead.
For example, compare the appearance of running `wfdb.plot_wfdb(wfdb.rdrecord('sample-data/100', sampto=1000), wfdb.rdann('sample-data/100', 'qrs', sampto=1000))` before and after this change.
=> Show annotation markers atop signals

MANIFEST.in, setup.py
I have also tested creating and uploading a distribution: https://test.pypi.org/project/wfdb2/0.0.0a10/
=> Replace references to README.rst with README.md

wfdb/plot/plot.py
If an error occurs while constructing a figure (e.g. because you passed invalid arguments to `plot_wfdb`), we should destroy the figure, rather than leaving a partially-completed figure in pyplot's internal queue where it will be unexpectedly displayed at some later time.  This should fix issue #347.
I think this'll do the right thing, but I've only tested it in the ordinary python interpreter; it should also be tested in jupyter.
=> Close partially-completed plot windows after an error

pyproject.toml
Issue #374: when you create a notebook in Google Colab (https://colab.research.google.com/), it comes pre-configured with a bunch of pip packages by default.  Some of those pre-installed packages will *conflict* with what you get if you try to run `pip install --upgrade matplotlib`.
Fortunately, the pre-installed environment already includes matplotlib, just not the latest version.
AFAIK, there should not be any problem using wfdb with matplotlib 3.2.2, so we can relax this requirement to make it easier for people to use the package with Colab.
Remember, when you run `pip install wfdb` in a fresh environment, it will always give you the *latest* versions that satisfy wfdb's dependencies.  So most people running `pip install wfdb` will still get matplotlib 3.5.2.
=> Relax matplotlib dependency for Google Colab

wfdb/io/record.py
`wfdb.rdrecord` currently sets an undocumented attribute `base_datetime`, but only if the record has a base date and a base time.
```
>>> r = wfdb.rdrecord('sample-data/n16')
>>> r.base_time
datetime.time(22, 34, 47)
>>> r.base_date
datetime.date(2006, 1, 1)
>>> r.base_datetime
datetime.datetime(2006, 1, 1, 22, 34, 47)
>>> r2 = wfdb.rdrecord('sample-data/3000003_0003')
>>> r2.base_time
datetime.time(19, 46, 25, 757000)
>>> r2.base_date
>>> r2.base_datetime
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'Record' object has no attribute 'base_datetime'
```
It is frequently convenient to have this attribute available, so:
1. Always set `base_datetime`; set it to None if either `base_date` or `base_time` is None.
2. Define it as an aliased property so …
=> Add base_datetime property

docs/io.rst, docs/wfdb.rst, tests/test_record.py, wfdb/io/record.py
Add some convenience methods for converting between different representations of time:
- frame number (represented as an integer or float)
- elapsed time (represented as a timedelta)
- absolute time (represented as a datetime)
For example, if I want to see the signals for MIMIC-III patient 44083, between `2112-05-04 20:00:00` and `2112-05-04 20:05:00`, I might do this:
```
>>> rec_name = 'p044083-2112-05-04-19-50'
>>> pn_dir = 'mimic3wdb-matched/1.0/p04/p044083'
>>> header = wfdb.rdheader(rec_name, pn_dir=pn_dir)
>>> dt1 = datetime.datetime.fromisoformat('2112-05-04 20:00:00')
>>> dt2 = datetime.datetime.fromisoformat('2112-05-04 20:05:00')
>>> start = round(header.get_frame_number(dt1))
>>> end = round(header.get_frame_number(dt2))
>>> chunk = wfdb.rdrecord(rec_name, pn_dir=pn_dir, …
```
=> Convenience methods for time conversion

tests/test_plot.py
Add some test cases for wfdb.plot_wfdb.  Mostly we just check that it doesn't crash, but also check that it gives vaguely-reasonable X and Y plotting ranges.
plot.py coverage before: 571/978 lines
plot.py coverage after: 851/978 lines
=> Test cases for plot_wfdb

wfdb/io/_coreio.py
The posixpath module is used in _coreio.py but I mistakenly forgot to import it.  This breaks remote FLAC file access.
=> Add a missing import in _coreio.py

wfdb/plot/plot.py
In `plot_wfdb`, add an argument `sharex` which controls whether X axes are shared between subplots.
(This means that multiple channels will always appear time-aligned with each other, even if one channel starts or ends with a block of NaNs.  It also means that if you use the pan/zoom buttons to navigate, the channels will *stay* aligned with each other.)
`sharex=True` is generally desirable behavior; however, if the time units are *sample numbers* and the record is multi-frequency, then it's not possible (AFAICT) with matplotlib to have the axes synchronized while displaying different units on different subplots.  So we disable sharex by default in that case.
Finally, `plot_wfdb` will use `time_units="seconds"` by default, which I think is useful because it's consistent (across databases) …
=> Align signals horizontally in plot_wfdb (if possible)

wfdb/io/_header.py, wfdb/io/_signal.py, wfdb/io/record.py, wfdb/io/util.py, wfdb/plot/plot.py, wfdb/processing/basic.py
No new logic. Just moving stuff to clean up the core modules.
=> Move some general functions to a util module and clean up some imports

tests/test_annotation.py, wfdb/io/annotation.py
Fixes #399
Take custom labels into account in encoding, should they exist by temporarily creating a larger version of ann_label_table including custom labels.
=> Allow custom labels in field2bytes

tests/test_annotation.py, wfdb/io/annotation.py, wfdb/io/record.py
@tompollard found that ambiguous backslashes give DeprecationWarnings on his system.
(Not that I think there is any danger of this behavior changing in python, but I think it's fair to say this syntax is confusing and should be avoided.)
I.e.: `"\s\n"` is a three-character string (equal to `"\\s\n"`).  If what you mean is `"\\s\n"`, it's better to write that and be unambiguous.
`r"\s\n"` is a four-character string (`"\\s\\n"`) but is interpreted by `re.compile` as equivalent to `"\\s\n"`.  So when writing regular expression patterns it's best to use `r` strings if possible.
=> Avoid ambiguous backslashes in regular expression strings

tests/test_record.py, wfdb/io/_signal.py
When converting physical (floating-point) values to digital (integer) values, we generally want to round to the nearest integer, not truncate towards zero.
(Translating floating-point data to integers is *more complicated than you'd think*, but we should try to avoid creating new sources of errors.)
One example:
```
>>> p = wfdb.rdrecord('sample-data/v102s', physical=True)
>>> d = wfdb.rdrecord('sample-data/v102s', physical=False)
>>> p.adc() == d.d_signal
array([[ True,  True,  True,  True],
[ True,  True, False,  True],
[ True,  True,  True,  True],
...,
[ True,  True,  True,  True],
[ True,  True,  True,  True],
[ True,  True,  True,  True]])
```
(we would of course expect these arrays to be equal.)
This fixes issue #418.
*edit: I am not good at copy and paste*
=> Round sample values in physical-to-digital conversion

tests/test_record.py, wfdb/io/_header.py, wfdb/io/_signal.py, wfdb/io/record.py
This is another mixed bag of changes to `wfdb.wrsamp` and `Record.wrsamp`.
The main goal here is to allow writing compressed (FLAC) signal files.
Just as with reading signal files, this requires rearranging the input data (`d_signal` or `e_d_signal`) into the format required by the soundfile package.  Just as with reading signal files, this is not done as efficiently as it could be (in fact, none of the formats in `wr_dat_file` are implemented as efficiently as they could be.)
It's worth noting that `soundfile` doesn't provide a way to set the compression level or other parameters.  Setting the compression level, at least, should be easy to implement if somebody wanted to.  The `libsndfile` default appears to be level 5 (the same default as `libwfdb` and the `flac` command-line tool.) …
=> FLAC output and assorted wrsamp improvements

wfdb/io/convert/edf.py
The [edf specifications](https://www.edfplus.info/specs/edf.html) notes all strings being 'ascii'. 
By default, `decode()` uses the 'utf-8' encoding. In some cases, this can cause decoding issues:
```
File ~/Library/Caches/pypoetry/virtualenvs/workspace-lukas-kum-5zRav6QH-py3.9/lib/python3.9/site-packages/wfdb/io/convert/edf.py:262, in read_edf(record_name, pn_dir, header_only, verbose, rdedfann_flag)
259 physical_dims = []
260 for _ in range(n_sig):
261     physical_dims.append(
--> 262         struct.unpack("<8s", edf_file.read(8))[0].decode().strip()
263     )
264 if verbose:
265     print("Physical Dimensions: {}".format(physical_dims))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte
```
Arguably, the encoding `ascii` should be used. However, …
=> When reading edf, decode all strings using 'unicode_escape'.

tests/test_record.py, wfdb/io/_header.py, wfdb/io/_signal.py, wfdb/io/record.py
There are a couple of ways to write a record using this package.  One is `wfdb.wrsamp`, the other is creating a `Record` object and calling the `wrsamp` method.
`Record.wrsamp` was, I think, meant to be more low-level and perhaps only intended for internal use of the package.  But for various reasons, applications may want or need to call this method directly.  So I think we need to support it, and make it more fool-proof; in particular, this method shouldn't generate *invalid* WFDB records even if the application supplies wrong parameters.
Here I address two of those parameters - `checksum` and `samps_per_frame`.
Typically, `checksum` is set by `wfdb.rdrecord`.  But naturally, the input data may have been *modified* (explicitly by the application, or implicitly e.g. by `smooth_frames`) …
=> Set correct checksums and samps_per_frame in Record.wrsamp

wfdb/io/record.py
Noticed that the example code for `wfdb.rdheader` seemed to be out of date - updated it to match the actual function signature.
=> Correct example code for rdheader

.github/workflows/run-tests.yml, wfdb/io/convert/edf.py
We decided a while ago to require code in this project to be formatted using `black`.
Fix the style of `edf.py` accordingly.  Require correct formatting for future pull requests.
=> Fix code style

pyproject.toml, tests/test_processing.py, wfdb/io/_header.py, wfdb/io/_signal.py, wfdb/io/annotation.py, wfdb/io/convert/edf.py, wfdb/io/convert/wav.py, wfdb/io/record.py, wfdb/processing/hr.py, wfdb/processing/qrs.py
Currently, all versions are capped, because the caret `^` operator also introduces an upper bound. In this PR, I replaced `^` with `>=`, which continues to use the same lower bounds, but removes any upper bound.
=> Remove version caps

tests/test_record.py
We should be able to read and write data with more than 8 channels to formats 508, 516, and 524. This test verifies that the digital signal generated when writing to format 516 is identical to the original signal loaded in from a sample record in format 16.
Should catch bugs like those fixed in #450
=> Add a test to check if wrsamp can write more than 8 channels to format 516

wfdb/processing/hr.py
This fixes issue #453 by using 64-bit integers on all platforms.  (64-bit integers are way overkill for storing RR intervals, but I think it's wise to keep it simple and use 64-bit integers for all types of sample intervals.)
This is a pretty simple fix, but looking at the code I also notice there are a couple of significant issues with this function:
- Unlike the ann2rr program, this function *only* considers the timestamps of the input annotations - it doesn't check whether they're QRS annotations or some other type of annotations (e.g. NOTE or RHYTHM).
- *Like* the ann2rr program, this function includes the interval between the first annotation and the start of the record.
As a result, when you look at Lucas's example in the docstring:
```
>>> wfdb.ann2rr('sample-data/100', 'atr', …
```
=> Use int64 instead of int for ann2rr

.github/workflows/run-tests.yml, wfdb/io/annotation.py
Using the equality operator with an empty list will result in the following error.
ValueError: operands could not be broadcast together with shapes (28,) (0,)
Using len() and inverting the logic avoids this issue.
=> bug-fix: Numpy ValueError when cheking empty list equality

wfdb/io/annotation.py
Current version of Pandas will throw the following error when indexing using a set.
TypeError: Passing a set as an indexer is not supported. Use a list instead.
=> bug-fix: Pandas set indexing error

wfdb/io/record.py
Fix for MIT-LCP/wfdb-python/issues/452
Using os.sep on Windows fails here because we are specifically searching for "/" as a separator
=> fix for MIT-LCP/wfdb-python/issues/452

docs/conf.py, docs/requirements.txt
Closes #471
This changeset adds `numpydoc` to the documentation build requirements, better distinguishing between parameters and return values.
Typical function documentation before this changeset:
After this changeset:
Note that this does produce **some Sphinx errors and warnings** when building the documentation, generally because `wfdb` is not following `numpydoc` style _exactly_. Most of them look like small tweaks, many of them can probably be resolved by removing unnecessary indentation or introducing a literal code block. I'll leave that to the maintainers.
<details>
<summary>click for build log</summary>
```
Running Sphinx v4.5.0
making output directory... done
[autosummary] generating autosummary for: changes.rst, convert.rst, index.rst, installation.rst, io.rst, plot.rst, …
```
=> Use numpydoc to render documentation

tests/test_record.py, wfdb/io/_signal.py
Fix several bugs in `Record.adc`:
1. Previously, the function would try to convert all samples to integers and then, for any samples that were NaN, replace the corresponding elements with the appropriate sentinel value.  Even though this was probably safe in most cases, casting NaN to an integer is implementation-defined behavior, and raises a warning by default (issue #480).
2. NaN just plain wasn't handled for the `inplace=True, expanded=False` case.  (Currently, we don't use `inplace=True` anywhere internally; although it saves a bit of memory, it's destructive and so it's probably wise for high-level functions like `wrsamp` to avoid it.)
3. The `expanded=True` case relied on `self.n_sig` (in contrast to `expanded=False`, which operates based on the dimensions of `p_signal`.)  This …
=> Fix NaN handling in Record.adc, and other fixes

pyproject.toml
As discussed in #493, numpy v2.0.0 introduces a breaking change for WFDB: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion. 
This pull request sets an upper bound on the numpy version as a temporary fix (`numpy = ">=1.10.1,<2.0.0"`).
=> Set upper bound on Numpy version (numpy = ">=1.10.1,<2.0.0"). Ref #493.

.github/workflows/run-tests.yml
The "[run tests](https://github.com/MIT-LCP/wfdb-python/blob/main/.github/workflows/run-tests.yml)" GitHub workflow is raising [several warnings](https://github.com/MIT-LCP/wfdb-python/actions/runs/9783079800) about deprecated actions:
e.g.
> `[build (ubuntu-latest, 3.9)](https://github.com/MIT-LCP/wfdb-python/actions/runs/9783079800/job/27011340622)
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/[build (ubuntu-latest, 3.9)](https://github.com/MIT-LCP/wfdb-python/actions/runs/9783079800/job/27011340622)
The following actions uses Node.js version which is …
=> Update actions to use actions/checkout@v3 and actions/setup-python@v4.

tests/io/test_convert.py, wfdb/io/convert/csv.py
As discussed in https://github.com/MIT-LCP/wfdb-python/issues/490, https://github.com/MIT-LCP/wfdb-python/blob/34b989e08435c1a82d31bdd2800c4c14147e3e93/wfdb/io/convert/csv.py#L10 currently "strips the path from the input .csv, then writes the output to .dat and .hea".
It's inconvenient not to be able to specify the output directory. This pull request adds a new `output_dir` argument to the `csv_to_wfdb` function. By default `output_dir` is set to None, which will maintain backwards compatibility. Setting `output_dir` to a directory will mean that output files are saved to this directory.
I have set this to a WIP, because I haven't tested the new behaviour (other than running `pytest`). @jshaffer94247, if you have an opportunity to test the fix, I'd appreciate your feedback.
=> Add write_dir argument to csv_to_wfdb. Fixes #67.

tests/test_annotation.py, wfdb/io/convert/edf.py, wfdb/io/download.py, wfdb/io/record.py
I've fixed a few warnings related to
- deprecated functions
- unclosed files
- unclosed multiprocessing pool
Now all tests pass without warnings (and errors of course).
=> Fix warnings

wfdb/io/annotation.py
As discussed in https://github.com/MIT-LCP/wfdb-python/issues/493, numpy v2.0 introduced changes to type promotion rules: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion
Running pytest with `numpy==2.0.2` and `NPY_PROMOTION_STATE=weak_and_warn` raises the following warnings for wfdb/io/annotation.py:
```
/Users/tompollard/projects/wfdb-python/wfdb/io/annotation.py:2222: UserWarning: result dtype changed due to the removal of value-based promotion from NumPy. Changed from int64 to uint8.
while filebytes[bpi, 1] >> 2 == 59:
/Users/tompollard/projects/wfdb-python/wfdb/io/annotation.py:2239: UserWarning: result dtype changed due to the removal of value-based promotion from NumPy. Changed from int64 to uint8.
label_store = filebytes[bpi, 1] >> 2 …
```
=> Change in type promotion. Fixes to annotation.py

wfdb/io/_signal.py
As discussed in https://github.com/MIT-LCP/wfdb-python/issues/493, numpy v2.0 introduced changes to type promotion rules: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion
Running pytest with `numpy==2.0.2` and `NPY_PROMOTION_STATE=weak_and_warn` raises the following warning for wfdb/io/_signal.py:
```
tests/test_record.py::TestRecord::test_1a
/Users/tompollard/projects/wfdb-python/wfdb/io/_signal.py:2374: UserWarning: result dtype changed due to the removal of value-based promotion from NumPy. Changed from int32 to int16.
d_signal[d_signal < 0] = d_signal[d_signal < 0] + 65536
```
The changes in this pull request address these issues by explicitly casting the type. I also make a couple of minor modifications for efficiency (switching to inplace …
=> Change in type promotion. Fixes to _signal.py

tests/test_record.py
We want to test that both reading and writing work correctly for all supported formats (although currently some binary formats are completely unsupported for writing.)
Previous test cases covered formats 80, 212, 16, and 24 (and the FLAC formats) but did not cover format 32.
=> Test round-trip write/read of supported binary formats

wfdb/io/_header.py
Corrected misordered arguments in util.lines_to_file. Added 'list' as allowed types for seg_name and seg_len, for when writing MultiSegmentRecords.
=> Corrected typo and extended allowed types for MultiSegmentRecord

wfdb/io/_signal.py
This PR updates `calc_adc_params` to allow an expanded physical signal to be passed. Previously only a non-expanded signal was allowed. The function will now calculate the `adc_gain` and `baseline` for `p_signal` or `e_p_signal`. 
I check for the signal that is not `None` and then compute the gain and baseline. I moved the calculation itself to a new function `calc_adc_gain_baseline` so we could call it for either signal type.
=> Allow expanded physical signal in `calc_adc_params`

tests/test_record.py, wfdb/io/_signal.py, wfdb/io/record.py
This PR adds the capability for writing signals with unique samples per frame (`samps_per_frame`) to `wfdb.io.wrsamp`. This is typically the function that is used to write WFDB files. This was previously only possible to do by creating a Record first and using its `wrsamp` method to do the write. 
@bemoody , I do feel like checking that the frames were uniform took a bit of extra code. I'm happy to leave it like this but also open to discussing other approaches. 
I've added a couple of tests to check that this continues to work as expected.
=> Add capability to write signal with unique `samps_per_frame` to `wfdb.io.wrsamp`

wfdb/processing/qrs.py
=> copy ricker wavelet from scipy which removed it from version 1.15.0

docs/conf.py, docs/requirements.txt, pyproject.toml
readthedocs [is failing](https://app.readthedocs.org/projects/wfdb/builds/23195231/) with the following error: 
```
Running Sphinx v4.5.0
loading translations [en]... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/wfdb/envs/latest/lib/python3.9/site-packages/sphinx/registry.py", line 438, in load_extension
metadata = setup(app)
File "/home/docs/checkouts/readthedocs.org/user_builds/wfdb/envs/latest/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py", line 230, in setup
app.require_sphinx('5.0')
File "/home/docs/checkouts/readthedocs.org/user_builds/wfdb/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 393, in require_sphinx
raise VersionRequirementError(version)
sphinx.errors.VersionRequirementError: 5.0
The …
```
=> Bump Sphinx to 7.0.0

.github/workflows/docs.yml
This PR updates the Ubuntu runner for the Read The Docs workflow to the next stable version (22.04) since the current version 20.04 was deprecated two days ago:
`This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15.`
=> Read The Docs workflow - upgrade from deprecated Ubuntu version

docs/requirements.txt
Currently the Read The Docs pages for this repo aren't providing the detailed information for the functions (only the landing page is working as expected). The Read The Docs build says that it succeeded but gives errors about not being able able to find the `fsspec` module, see the [log](https://app.readthedocs.org/api/v2/build/27889860.txt) for more detail. 
I've added `fsspec` to `docs/requirements.txt` to fix this issue.
=> Add `fsspec` to Read The Docs requirement

wfdb/plot/plot.py
When running the latest version of the code, the example didn't run without adding these two arguments.
=> Correct docstring for plot.py

.github/workflows/style.yml, .github/workflows/test.yml
Currently, style checks are integrated with functional tests in the same workflow. This meant that any style issues cause the entire test suite to fail.
This pull request:
- Creates a new workflow file `.github/workflows/style.yml` for style checks
- Removes style check step from the test workflow
The benefit of making this change is that it becomes easier to identify whether issues are related to code style or functionality.
=> Split style checks into separate workflow
